default:
  tags: [cpu]

stages:
   - build_in_docker
   - test
   - test_aarch64_910B2_py3.11
   - test_aarch64_910B2_py3.12 # Serialize the py3.11 and py3.12 tests otherwise CI fails!


# Define the workflow rules manually to make sure only a single pipeline
# is created for each MR update. Without that, GitLab creates one pipeline
# for branch update and one for MR update.
workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: always
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_DRAFT'
      when: never
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always
    - when: never


.build_config: &build_config
  image: quay.io/ascend/cann:8.5.1-910b-ubuntu22.04-${PYTHON_VERSION}
  parallel:
    matrix:
      - {PYTHON_VERSION: py3.11}
      - {PYTHON_VERSION: py3.12}
  before_script:
    - source /usr/local/Ascend/ascend-toolkit/set_env.sh
    - pip3 install pyyaml setuptools pytest packaging
    - pip3 install -r requirements.txt

build_docker:
  stage: build_in_docker
  tags:
    - cpu # Build docker using CPU
  <<: *build_config
  script:
    - make build_wheel

build_and_test_x86_910B4:
  tags:
    - docker_npu # Build and test on-device NPU (x86-64 / 910B4)
  <<: *build_config
  script:
    - make setup_once
    - make build_wheel
    - pip install pto_kernels*.whl
    - python3 -m pytest -v tests/

build_and_test_aarch64_910B2_py3.11:
  image: quay.io/ascend/cann:8.5.1-910b-ubuntu22.04-py3.11
  stage: test_aarch64_910B2_py3.11
  tags:
    - docker_npu_910B2 # Build and test on-device (aarch64 / 910B2)
  before_script:
    - source /usr/local/Ascend/ascend-toolkit/set_env.sh
    - pip3 install pyyaml setuptools pytest packaging
    - pip3 install -r requirements.txt
  script:
    - make setup_once
    - make build_wheel
    - pip install pto_kernels*.whl
    - python3 -m pytest -v tests/

build_and_test_aarch64_910B2_py3.12:
  image: quay.io/ascend/cann:8.5.1-910b-ubuntu22.04-py3.12
  stage: test_aarch64_910B2_py3.12
  tags:
    - docker_npu_910B2 # Build and test on-device (aarch64 / 910B2)
  before_script:
    - source /usr/local/Ascend/ascend-toolkit/set_env.sh
    - pip3 install pyyaml setuptools pytest packaging
    - pip3 install -r requirements.txt
  script:
    - make setup_once
    - make build_wheel
    - pip install pto_kernels*.whl
    - python3 -m pytest -v tests/

######################################
# On-device test of examples/jit_cpp #
######################################
include:
  - '.gitlab-ci.examples.yml'
