[pytest]
norecursedirs = .git build src*
filterwarnings =
    ignore::UserWarning
    ignore::DeprecationWarning:torch # Silence "DeprecationWarning: `torch.jit.script_method` is deprecated. Please switch to `torch.compile` or `torch.export`."
