from pto_kernels.ops.common import tilekernels_meta


META = tilekernels_meta(
    family='moe',
    name='topk',
    builders=['topk_gate', 'topk_sum_and_topk_group_idx'],
    configs=[{'case': 'topk_gate',
  'configs': [{'num_experts': 72, 'num_topk': 6, 'sort_ncols': 128},
              {'num_experts': 32, 'num_topk': 6, 'sort_ncols': 32},
              {'num_experts': 64, 'num_topk': 6, 'sort_ncols': 128},
              {'num_experts': 96, 'num_topk': 6, 'sort_ncols': 128},
              {'num_experts': 16, 'num_topk': 6, 'sort_ncols': 32},
              {'num_experts': 36, 'num_topk': 6, 'sort_ncols': 128},
              {'num_experts': 108, 'num_topk': 6, 'sort_ncols': 128},
              {'num_experts': 128, 'num_topk': 6, 'sort_ncols': 128},
              {'num_experts': 144, 'num_topk': 6, 'sort_ncols': 512},
              {'num_experts': 256, 'num_topk': 8, 'sort_ncols': 512}]},
 {'case': 'topk_sum_and_topk_group_idx',
  'configs': [{'group_score_sort_ncols': 32,
               'group_sort_ncols': 32,
               'num_experts': 72,
               'num_group_sum_topk': 1,
               'num_groups': 4,
               'num_topk_groups': 2},
              {'group_score_sort_ncols': 32,
               'group_sort_ncols': 32,
               'num_experts': 72,
               'num_group_sum_topk': 1,
               'num_groups': 4,
               'num_topk_groups': 4},
              {'group_score_sort_ncols': 32,
               'group_sort_ncols': 32,
               'num_experts': 72,
               'num_group_sum_topk': 2,
               'num_groups': 4,
               'num_topk_groups': 2},
              {'group_score_sort_ncols': 32,
               'group_sort_ncols': 32,
               'num_experts': 72,
               'num_group_sum_topk': 2,
               'num_groups': 4,
               'num_topk_groups': 4},
              {'group_score_sort_ncols': 32,
               'group_sort_ncols': 32,
               'num_experts': 72,
               'num_group_sum_topk': 1,
               'num_groups': 8,
               'num_topk_groups': 2},
              {'group_score_sort_ncols': 32,
               'group_sort_ncols': 32,
               'num_experts': 72,
               'num_group_sum_topk': 1,
               'num_groups': 8,
               'num_topk_groups': 4},
              {'group_score_sort_ncols': 32,
               'group_sort_ncols': 32,
               'num_experts': 72,
               'num_group_sum_topk': 2,
               'num_groups': 8,
               'num_topk_groups': 2},
              {'group_score_sort_ncols': 32,
               'group_sort_ncols': 32,
               'num_experts': 72,
               'num_group_sum_topk': 2,
               'num_groups': 8,
               'num_topk_groups': 4},
              {'group_score_sort_ncols': 32,
               'group_sort_ncols': 32,
               'num_experts': 72,
               'num_group_sum_topk': 1,
               'num_groups': 12,
               'num_topk_groups': 2},
              {'group_score_sort_ncols': 32,
               'group_sort_ncols': 32,
               'num_experts': 72,
               'num_group_sum_topk': 1,
               'num_groups': 12,
               'num_topk_groups': 4},
              {'group_score_sort_ncols': 32,
               'group_sort_ncols': 32,
               'num_experts': 72,
               'num_group_sum_topk': 2,
               'num_groups': 12,
               'num_topk_groups': 2},
              {'group_score_sort_ncols': 32,
               'group_sort_ncols': 32,
               'num_experts': 72,
               'num_group_sum_topk': 2,
               'num_groups': 12,
               'num_topk_groups': 4},
              {'group_score_sort_ncols': 32,
               'group_sort_ncols': 128,
               'num_experts': 256,
               'num_group_sum_topk': 1,
               'num_groups': 4,
               'num_topk_groups': 2},
              {'group_score_sort_ncols': 32,
               'group_sort_ncols': 128,
               'num_experts': 256,
               'num_group_sum_topk': 1,
               'num_groups': 4,
               'num_topk_groups': 4},
              {'group_score_sort_ncols': 32,
               'group_sort_ncols': 128,
               'num_experts': 256,
               'num_group_sum_topk': 2,
               'num_groups': 4,
               'num_topk_groups': 2},
              {'group_score_sort_ncols': 32,
               'group_sort_ncols': 128,
               'num_experts': 256,
               'num_group_sum_topk': 2,
               'num_groups': 4,
               'num_topk_groups': 4},
              {'group_score_sort_ncols': 32,
               'group_sort_ncols': 32,
               'num_experts': 256,
               'num_group_sum_topk': 1,
               'num_groups': 8,
               'num_topk_groups': 2},
              {'group_score_sort_ncols': 32,
               'group_sort_ncols': 32,
               'num_experts': 256,
               'num_group_sum_topk': 1,
               'num_groups': 8,
               'num_topk_groups': 4},
              {'group_score_sort_ncols': 32,
               'group_sort_ncols': 32,
               'num_experts': 256,
               'num_group_sum_topk': 2,
               'num_groups': 8,
               'num_topk_groups': 2},
              {'group_score_sort_ncols': 32,
               'group_sort_ncols': 32,
               'num_experts': 256,
               'num_group_sum_topk': 2,
               'num_groups': 8,
               'num_topk_groups': 4},
              {'group_score_sort_ncols': 32,
               'group_sort_ncols': 32,
               'num_experts': 256,
               'num_group_sum_topk': 1,
               'num_groups': 16,
               'num_topk_groups': 2},
              {'group_score_sort_ncols': 32,
               'group_sort_ncols': 32,
               'num_experts': 256,
               'num_group_sum_topk': 1,
               'num_groups': 16,
               'num_topk_groups': 4},
              {'group_score_sort_ncols': 32,
               'group_sort_ncols': 32,
               'num_experts': 256,
               'num_group_sum_topk': 2,
               'num_groups': 16,
               'num_topk_groups': 2},
              {'group_score_sort_ncols': 32,
               'group_sort_ncols': 32,
               'num_experts': 256,
               'num_group_sum_topk': 2,
               'num_groups': 16,
               'num_topk_groups': 4}]}],
    source='tilekernels/moe/topk',
    notes="PTO-DSL follows the PTO-ISA manual TopK structure: tfillpad_expand with PadValue::Min pads exact TileKernels expert counts to PTO sort widths, sort32 attaches a uint32 index vector, mrgsort merges, and gather extracts index lanes. PTO-Gym validation currently uses uint32 output indices; TileKernels torch API returns int64. Grouped TopK now uses PTO sort/pad/gather primitives twice: first inside each group to sum the top expert scores, then over per-group sums to select group indices. PTO-Gym validation currently uses uint32 group indices because PTO sort exposes uint32 index lanes; TileKernels' public torch API returns int64.",
)
