name: CI (A5)

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: "0 2 * * *"   # runs every day at 02:00 UTC
  workflow_dispatch:       # allows manual trigger
  pull_request:

jobs:
  build_single_kernel_a5:
    name: Build kernel_${{ matrix.kernel }} for A5 (py${{ matrix.python_version }})
    runs-on: ubuntu-latest
    continue-on-error: true

    strategy:
      fail-fast: false
      matrix:
        kernel:
          - abs
          - batch_matrix_square
          - csr_gather
          #- flash_attention
          - gdn_chunk_cumsum
          - gdn_chunk_h
          - gdn_chunk_o
          - gdn_scaled_dot_kkt
          - gdn_wy_fast
          - kda_chunk_h
          - kda_chunk_o
          - kda_gate_cumsum
          - kda_kkt
          - kda_wy
          - scan_ul1
          - simple_matmul
          - swiglu
          - tri_inv_col_sweep
          - tri_inv_ns
          - tri_inv_rec_unroll
          - tri_inv_trick
        arch: [ x86_64 ]
        python_version: [ 3.12 ]

    container:
      image: quay.io/ascend/cann:9.1.0-950-ubuntu22.04-py${{ matrix.python_version }}
    steps:
      - name: Show OS
        run: cat /etc/os-release

      - name: Checkout code
        uses: actions/checkout@v4

      - name: make compile_a5_${{ matrix.kernel }}
        shell: bash
        run: |
          source /usr/local/Ascend/ascend-toolkit/set_env.sh
          source /usr/local/Ascend/nnal/atb/set_env.sh
          export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/Ascend/ascend-toolkit/latest/`uname -i`-linux/devlib # to avoid libascend_hal.so issue
          make compile_a5_${{ matrix.kernel }}

      - name: Show built shared library
        run: ls -lh build/lib/libkernel_${{ matrix.kernel }}.so
